import type { VehicleHorizontalCardViewModel } from "@/src/entities/vehicle";

export const mockVehicles: VehicleHorizontalCardViewModel[] = [
  {
    badge: "New",
    brand: "BMW",
    features: ["Leather interior", "Panoramic roof", "Adaptive cruise", "360 parking"],
    fuel: "Diesel",
    href: "/vehicles/bmw-530d-xdrive",
    id: "bmw-530d-xdrive",
    location: "Vilnius",
    mileage: "48,000 km",
    postedAt: "2 hours ago",
    power: "265 hp",
    price: "29,900 EUR",
    priceNote: "Approx. 103,200 Lt",
    title: "5 Series 530d xDrive Luxury",
    transmission: "Automatic",
    views: "1,842",
    year: "2022",
  },
  {
    brand: "Toyota",
    features: ["360 camera", "Heated seats", "LED lights", "Apple CarPlay"],
    fuel: "Hybrid",
    href: "/vehicles/toyota-camry-hybrid",
    id: "toyota-camry-hybrid",
    location: "Kaunas",
    mileage: "62,000 km",
    postedAt: "5 hours ago",
    power: "218 hp",
    price: "22,500 EUR",
    priceNote: "Approx. 77,600 Lt",
    title: "Camry 2.5 Hybrid Comfort+",
    transmission: "Automatic",
    views: "924",
    year: "2021",
  },
  {
    badge: "VIP",
    brand: "Volkswagen",
    features: ["Climate control", "Apple CarPlay", "Parking sensors"],
    fuel: "Petrol",
    href: "/vehicles/vw-golf-life-plus",
    id: "vw-golf-life-plus",
    location: "Siauliai",
    mileage: "85,000 km",
    postedAt: "Yesterday",
    power: "150 hp",
    price: "14,200 EUR",
    priceNote: "Approx. 49,000 Lt",
    title: "Golf 1.5 TSI Life Plus DSG",
    transmission: "Manual",
    views: "548",
    year: "2020",
  },
];
